name: ✨ Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: dropdown
    id: type
    attributes:
      label: Request type
      options:
        - New feature
        - Enhancement to existing feature
        - UX/UI improvement
        - Performance improvement
        - Developer experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Urgent
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: "Add/change..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Other approaches..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context / mockups
      description: Links, screenshots, examples.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues to avoid duplicates.
          required: true
